import discord
from discord.ext import commands
client=commands.Bot(command_prefix= '<')
@client.event
async def on_ready():
    print("bot is ready")
@client.command()
async def take(ctx):
    import random
    objects = {
        1: "Tartarus",
        2: "The Golden",
        3: "Zodiac",
        4: "Kenos",
        5: "Crimson Planet",
        6: "The Rupture",
        7: "Renevant",
        8: "Thinking Space",
        9: "Calculator Core",
        10: "SARY NEVER CLEAR",
        11: "Cold Sweat",
        12: "Cognition",
        13: "Lucid Nightmares",
        14: "Bloodlust",
        15: "Ragnarok",
        16: "Deimos",
        17: "Aronia",
        18: "Arctic Lights",
        19: "kowareta",
        20: "Visible Ray",
        21: "Aquatic Auroras",
        22: "Wasureta",
        23: "Ouroboros",
        24: "The Yandere",
        25: "Sigma",
        26: "Plasma Pulse Finale",
        27: "Hyper Paracosm",
        28: "Gamma",
        29: "Necromancer",
        30: "Eternal Moment",
        31: "Spectrum Cyclone",
        32: "Spacial Rend",
        33: "Sonic Wave",
        34: "Generic Wave",
        35: "Edge of the Blade",
        36: "Macabre",
        37: "Cybernetic Crescent",
        38: "Timor",
        39: "Yatagrasu",
        40: "Omega",
        41: "Titan Complex",
        42: "Omicron",
        43: "WOW",
        44: "Rage",
        45: "Erebus",
        46: "Devil Vortex",
        47: "Dark Flare",
        48: "Lucid Chaos",
        49: "Celestial Force",
        50: "Sunset Sandstorm",
        51: "xo",
        52: "ZAPHKIEL",
        53: "Molten Gear",
        54: "Altered Ascent",
        55: "Digital Descent",
        56: "Paroxysm",
        57: "Tapwreck",
        58: "Mirrored Calamity",
        59: "Freedom08",
        60: "Cadrega City",
        61: "Stalemate Redux",
        62: "Catalyze",
        63: "Step To Hell",
        64: "Photovoltaic II",
        65: "Killbot",
        66: "Delta Interface",
        67: "Factory Realm X",
        68: "Tempered Steel",
        69: "Fabrication",
        70: "Demonicat",
        71: "Ethereal Artifice",
        72: "Artificial Ascent",
        73: "Auditory Breaker",
        74: "BBBBBBBBBBBBBBBBBBBB",
        75: "Missing Benefits",
        76: "Aesthetic",
        77: "Occult Outcry",
        78: "Chromatic Haze",
        79: "Quantum Processing",
        80: "Glowy",
        81: "Ziroikabi",
        82: "Rate Demon",
        83: "Void Wave",
        84: "Bausha Vortex",
        85: "Balengu Vortex",
        86: "Sinister Incision",
        87: "Yuh",
        88: "Belloq",
        89: "The Hell Field",
        90: "Carcano",
        91: "Black Blizzard",
        92: "Ziroikapi",
        93: "Hatred",
        94: "distraught",
        95: "The Hell Inferno",
        96: "Cadrega Mode",
        97: "Hyper Paradox",
        98: "Dolos",
        99: "BuTiTi III",
        100: "Furious Flames",
        101: "Tenth Circle",
        102: "Surge of the Shield",
        103: "super probably level",
        104: "Libertas",
        105: "Audio Expulsion",
        106: "Astral Divinty",
        107: "2 1 1",
        108: "Bass Cave",
        109: "Berserk",
        110: "SINGULARITY",
        111: "Anoxysm",
        112: "SubSonic",
        113: "ikaros",
        114: "Mujigae",
        115: "The Hell Zone",
        116: "Betrayal of Destiny",
        117: "Surge of Memories",
        118: "Shock Therapy",
        119: "Glitched Memories",
        120: "Infernal Abyss",
        121: "Athanatos",
        122: "SPEEDRUN",
        123: "Galactic Shift",
        124: "Shock Breaker",
        125: "Breakout Redux",
        126: "Ithacropolis",
        127: "The Hell World",
        128: "TeaM Z",
        129: "Fabricated Thoughts",
        130: "Disentombed",
        131: "MadMasion",
        132: "Mystic",
        133: "The Hell Origin",
        134: "EnvY",
        135: "Asmodeus",
        136: "Low Death",
        137: "Fusion Z",
        138: "DARKENED",
        139: "Falcon16",
        140: "Carnage Mode",
        141: "Alpha Baa X",
        142: "VendetTa",
        143: "Dimension Breaker",
        144
        : "Phobos",
        145: "Shibui",
        146: "Sakupen Hell",
        147: "Dimensional Breaking",
        148: "Ancestral Calamity",
        149: "Silentium Gradas",
        150: "Blade of Justice",
        151: "Mix991",
        152: "Adr1anGD",
        153: "Temp",
        154: "Hixobit",
        155: "vp999",
        156: "AeonAir",
        157: "MinYong",
        158: "FigTheCat",
        159: "Lawnmower",
        160: "Sway",
        161: "Slithium",
        162: "Moosh",
        163: "stop",
        164: "NikNotNoob",
        165: "Rain22",
        166: "Timo",
        167: "CaveMelv",
        168: "Real",
        169: "TheTerrbonnie",
        170: "Brandon Larkin",
        171: "para",
        172: "Intel",
        173: "Prayoga",
        174: "Fhy1ron",
        175: "Plus0ne",
        176: "SnowBallerr",
        177: "Sowun",
        178: "Chief Keef",
        179: "cobrablitz",
        180: "Miro",
        181: "GMD6eez",
        182: "BoldStep",
        183: "Terakot",
        184: "Luciela",
        185: "Dorami",
        186: "DTDom",
        187: "KandyMan",
        188: "r973",
        189: "Seadawg",
        190: "lolwut",
        191: "HaydenX13",
        192: "iNeo",
        193: "TheRealEandis",
        194: "Dils Thik",
        195: "chattey",
        196: "PoweredByPie",
        197: "Grey749",
        198: "foundmyball",
        199: "Beastular",
        200: "Hotball1",
        201: "Spaces",
        202: "Sparky",
        203: "Blathers",
        204: "Tenebris",
        205: "skycrab",
        206: "GDultim8",
        207: "robotcheif",
        208: "Alphanetic",
        209: "vaen",
        210: "Pakki",
        211: "conski",
        212: "Derek46",
        213: "Plusxenon",
        214: "SkyJax",
        215: "Cewew",
        216: "SrGuillester",
        217: "Galaxy GD",
        218: "knoeppel",
        219: "poi",
        220: "Kevelia",
        221: "Swooker",
        222: "Spamdrew128",
        223: "BlazeRol",
        224: "realiosteelio",
        225: "Aether22",
        226: "Atomic",
        227: "Dagger",
        228: "BlazerWolfGD",
        229: "vinny",
        230: "Robin",
        231: "Luxer",
        232: "DiLeMa",
        233: "Zupreme",
        234: "Ishigiru",
        235: "AlejandroGD",
        236: "A11legiance",
        237: "Slashomi",
        238: "zDemented",
        239: "aedengmd",
        240: "Johnfree",
        241: "Axinity",
        242: "Spaceuk",
        243: "Teno",
        244: "Waivve",
        245: "BGram",
        246: "Nessid",
        247: "Naxrin",
        248: "Teris700",
        249: "Psychotix",
        250: "Ramppi",
        251: "Enzuu",
        252: "GMDomy",
        253: "Metalface221",
        254: "RicoLP",
        255: "BlackMG",
        256: "SebasLopezGD",
        257: "Lurox",
        258: "nainteils",
        259: "Bleamer",
        260: "takmaster",
        261: "npesta",
        262: "Enzeux",
        263: "BrutalSword107",
        264: "BlakeJM",
        265: "X99",
        266: "Nimbus",
        267: "samtaylor",
        268: "liternix",
        269: "ddddr",
        270: "vurz",
        271: "Stilluetto",
        272: "zPlasmalust",
        273: "NitrosHigh",
        274: "lappwv",
        275: "D3ltex",
        276: "CringyDylan",
        277: "skyzl",
        278: "Jaegerdd",
        279: "Xanii",
        280: "xeonzz",
        281: "ultracauaHD",
        282: "kotamon",
        283: "Varium",
        284: "Skarro",
        285: "Pablohh",
        286: "stardream999",
        287: "JakeN2436",
        288: "Finley",
        289: "Kv082",
        290: "Golden",
        291: "Wolfy",
        292: "Swiborg",
        293: "combi",
        294: "kapinapi",
        295: "Keir",
        296: "Gabs",
        297: "Doli",
        298: "CuTTer",
        299: "zMarc",
        300: "rWooshi",
        301: "IiCriSiSiI",
        302: "Roby",
        303: "rSteel",
        304: "ezvie",
        305: "TGM05",
        306: "Mullsy",
        307: "BigThunder556",
        308: "Zagros",
        309: "Joshua28",
        310: "Colorbolt",
        311: "Evilseph83",
        312: "Gizbro",
        313: "Ozzy",
        314: "Harry",
        315: "Doggie",
        316: "DibiiziCookie",
        317: "LuigiDB",
        318: "Sunix",
        319: "Simmyy",
        320: "Dosh7t",
        321: "Skullo",
        322: "MrSpaghetti",
        323: "Kainite",
        324: "Xylitol",
        325: "Ryth",
        326: "Pushenka",
        327: "VoTcHi",
        328: "Kurumi",
        329: "AlexDIRO",
        330: "TheUltraBlock",
        331: "Toka",
        332: "Joeingly",
        333: "Seturan",
        334: "Dolphy",
        335: "dice88",
        336: "GdWolvezz",
        337: "Sid125",
        338: "DiamondSplash",
        339: "Mycrafted",
        340: "GDonut",
        341: "rori",
        342: "Rainstorm",
        343: "TherZ",
        344: "Luqualizer",
        345: "Zeronium",
        346: "Spirtex",
        347: "Jeller",
        348: "BrianTheBurger",
        349: "ViewSonic",
        350: "Technical",
        351: "RG",
        352: "nSwish",
        353: "Topi",
        354: "xCreatorgoal",
        355: "EricVanWilderman",
        356: "Juniper",
        357: "NorkBork",
        358: "Xaro",
        359: "Mello",
        360: "Th13teen",
        361: "LukePixel",
        362: "Zepty",
        363: "UFWM",
        364: "fnm04",
        365: "PandaGD",
        366: "Camellia",
        367: "Geoxor",
        368: "Lukhash",
        369: "Dimrain47",
        370: "Creo",
        371: "MrKoolTrix",
        372: "Nightning",
        373: "XVminecraft77",
        374: "Solus",
        375: "Icedcave",
        376: "RyuDieDragon",
        377: "alkali"
    }
    level1 = (objects[random.randrange(1, 150)])
    level2 = (objects[random.randrange(1, 150)])
    person1 = (objects[random.randrange(151, 377)])
    person2 = (objects[random.randrange(151, 377)])
    randobj = (objects[random.randrange(1, 377)])
    takes = {
        1: level1 + " is so fucking free why is it above " + level2 + "???????",
        2: "fuck " + randobj,
        3: person1 + " is such an overrated creator",
        4: person1 + " is such an overrated artist",
        5: person1 + " is such an overrated youtuber",
        6: person1 + " is such an overrated player",
        7: "why do people like " + level1 + ", yall should play " + level2,
        8: "I hate " + person1,
        9: "I'd suck " + person1 + "'s dick",
        10: person1 + " is hotter than " + person2,
        11: "why isnt " + level1 + " top " + str(random.randrange(1, 50)),
        12: person1 + " is a better creator than " + person2,
        13: level1 + " is a fun and balanced level",
        14: "I think " + level1 + " is the best decorated level of all time",
        15: level1 + " is literally top 1",
        16: person1 + " makes better gameplay than " + person2,
        17: person1 + " is an asshole",
        18: "challenges take no skill",
        19: "why my pp shaped like mushrom",
        20: level1 + " would have been better if " + person1 + " verified it",
        21: level1 + " would be better on the challenge list",
        22: "i think " + person1 + " is probably gay",
        23: level1 + " is actually the easiest extreme",
        24: "I actually have evidence that " + person1 + " groomed a child",
        25: "what the fuck is " + randobj,
        26: level1 + " is an awful hardest",
        27: person1 + " should stop creating",
        28: "why is " + level1 + " actually good",
        29: level1 + " is unironically a medium demon",
        30: "if " + level1 + " was a person they would be " + person1,
        31: "why is " + person1 + " getting into drama every week",
        32: person1 + " is based",
        33: person1 + " looks like a weeb",
        34: person1 + " is a femboy",
        35: randobj + " is sus",
    }
    mytake = str(takes[random.randrange(1, 35)])
    print(mytake)
    await ctx.send(mytake)
    #token go there if u dum
client.run('ODE3OTM3MTM4ODM0MDc5Nzc0.YEQxUg.hnEY22Zre9F57JPIk_0g2G-Gkk8')
